---
- name: Template
  template:
    src: '{{ item.src }}'
    dest: '{{ item.dest }}'
    mode: '0755'
  with_items:
    - { src: 'docker-jenkins.sh.j2', dest: '/home/{{ ansible_user }}/docker-compose/jenkins/docker-jenkins.sh' }

- name: Install docker-jenkins
  shell:
    chdir: /home/{{ ansible_user }}/docker-compose/jenkins
    cmd: ./docker-jenkins.sh