---
- name: make directory
  file:
    path: "{{ jenkins.volumes.directory }}"
    state: directory
    owner: vagrant
    group: vagrant
    mode: 0777

- name: Container present
  docker_container:
    name: jenkins
    state: started
    restart_policy: always
    image: jenkins/jenkins
    ports:
      - "{{ jenkins.ports }}:8080"
      - "50000:50000"
    volumes:
      - "{{ jenkins.volumes.directory }}:/var/jenkins_home"
      - /var/run/docker.sock:/var/run/docker.sock