---
- name: Install python
  apt:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
    - python3
    - python3-pip

# tasks file for docker-harbor
- name: Make directory of harbor
  file:
      path: "{{ item }}"
      state: directory
      mode: '0755'
  with_items:
    - /certs
    - /data/cert
    - /data/cert/{{ ansible_host }}
    - /etc/docker/certs.d/{{ ansible_host }}

- name: Create CA
  shell: |
    openssl genrsa -out ca.key 4096
    openssl req -x509 -new -nodes -sha512 -days 3650 \
      -subj '/C=CN/ST=seoul/L=seoul/O="{{ ansible_user }}"/OU="{{ ansible_user }}"/CN="{{ ansible_host }}"' \
      -key ca.key \
      -out ca.crt

    openssl genrsa -out "{{ ansible_host }}".key 4096
    openssl req -sha512 -new \
      -subj '/C=CN/ST=seoul/L=seoul/O="{{ ansible_user }}"/OU="{{ ansible_user }}"/CN="{{ ansible_host }}"' \
      -key {{ ansible_host }}.key \
      -out {{ ansible_host }}.csr
  args:
    chdir: /certs

- name: Create v3.ext
  shell: echo "subjectAltName = IP:{{ ansible_host }},IP:127.0.0.1" > v3.ext
  args:
    chdir: /certs

- name: Create crt
  shell: |
    openssl x509 -req -sha512 -days 3650 \
      -extfile v3.ext \
      -CA ca.crt -CAkey ca.key -CAcreateserial \
      -in {{ ansible_host }}.csr \
      -out {{ ansible_host }}.crt
  args:
    chdir: /certs

- name: Create cert
  shell: |
    openssl x509 -inform PEM -in {{ ansible_host }}.crt -out {{ ansible_host }}.cert
  args:
    chdir: /certs

- name: Copy key
  shell: |
    cp {{ ansible_host }}.crt /data/cert/
    cp {{ ansible_host }}.key /data/cert/
    cp {{ ansible_host }}.cert /etc/docker/certs.d/{{ ansible_host }}/
    cp {{ ansible_host }}.key /etc/docker/certs.d/{{ ansible_host }}/
    cp ca.crt /etc/docker/certs.d/{{ ansible_host }}/
  args:
    chdir: /certs

- name: Unarchive harbor.tgz
  unarchive:
    src: https://github.com/goharbor/harbor/releases/download/v2.3.1/harbor-offline-installer-v2.3.1.tgz
    dest: "/"
    mode: '0755'
    remote_src: yes

- name: Template
  template:
    src: harbor.yml.j2
    dest: /harbor/harbor.yml
    mode: '0755'

- name: Install harbor
  shell: |
    ./install.sh --with-chartmuseum
  args:
    chdir: "/harbor"
    executable: /bin/bash