---
# tasks file for docker-gitlab
- name: Make directory of docker-compose
  file:
      path: "{{ item }}"
      state: directory
      mode: '0755'
  with_items:
    - {{ gitlab.dockerComposeDir }}

- name: Template
  template:
    src: docker-compose.yaml.j2
    dest: {{ gitlab.dockerComposeDir }}/docker-compose.yaml
    mode: '0755'

- name: Docker-compose up
  shell:
    chdir: {{ gitlab.dockerComposeDir }}
    cmd: docker-compose up -d