---
maria:
  enabled: true
  container:
    name: mariadb
  host: "{{ ansible_user }}"
  volumes: /home/vagrant/volumes
  image: mariadb:10.7
  root:
    pw: 1234
  user:
    id: "{{ ansible_user }}"
    pw: "{{ ansible_user }}"
  port: 53307

template:
  user:
    id: ansibleUser
    pw: ansibleUser
  database:
    name: AUTH_DB
  backup:
    database:
      name: AUTH_DB
    filepath: /dump/authdb.sql
  restore:
    database:
      name: AUTH_DB
    filepath: /dump/authdb.sql
