---
# tasks file for node-exporter
- name: Make directory of node-exporter
  file:
      path: "{{ item }}"
      state: directory
      mode: '0755'
  with_items:
    - {{ global.local.hostHome }}/node-exporter/

- name: download node-exporter
  unarchive:
    src: https://github.com/prometheus/node_exporter/releases/download/v1.7.0/node_exporter-1.7.0.linux-amd64.tar.gz
    dest: {{ global.local.hostHome }}/node-exporter/
    mode: '0755'
    remote_src: yes

- name: Install needs
  apt:
    name: "{{ packages }}"
    update_cache: yes
    state: present
  vars:
    packages:
    - dbus-x11
    - gnupg2
    - pass

- name: Move bin
  shell: |
    mv node_exporter-1.7.0.linux-amd64/node_exporter /usr/local/bin/
  args:
    chdir: "{{ global.local.hostHome }}/node-exporter/"

- name: Add User
  user:
    name: node_exporter
    state: present

- name: Make a config file about node exporter 
  template:
    src: node_exporter.service.j2
    dest: /etc/systemd/system/node_exporter.service
    mode: '0755'

- name: Run node-exporter
  shell: |
    systemctl daemon-reload
    systemctl start node_exporter
    systemctl enable node_exporter
  args:
    chdir: {{ global.local.hostHome }}/node-exporter/