---
# tasks file for docker-promethus-grafana
- name: Make directory of docker-compose
  file:
      path: "{{ item }}"
      state: directory
      mode: '0755'
  with_items:
    - {{ global.local.dockerComposeDir }}/docker-prometheus-grafana
    - {{ global.local.volume }}/prometheus

- name: Template
  template:
    src: '{{ item.src }}'
    dest: '{{ item.dest }}'
    mode: '0755'
  with_items:
    - { src: 'docker-compose.yaml.j2', dest: '{{ global.local.dockerComposeDir }}/docker-prometheus-grafana/docker-compose.yaml' }
    - { src: 'prometheus.yml.j2', dest: '{{ global.local.volume }}/prometheus/prometheus.yml' }

- name: Docker-compose up
  shell:
    chdir: {{ global.local.dockerComposeDir }}/docker-prometheus-grafana
    cmd: docker-compose up -d