---
# tasks file for docker-redmine
- name: Make directory of docker-compose
  file:
      path: "{{ item }}"
      state: directory
      mode: '0755'
  with_items:
    - {{ global.local.dockerComposeDir }}/redmine

- name: Template
  template:
    src: docker-compose.yaml.j2
    dest: {{ global.local.dockerComposeDir }}/redmine/docker-compose.yaml
    mode: '0755'

- name: Docker-compose up
  shell: docker-compose up -d
  args:
    chdir: {{ global.local.dockerComposeDir }}/redmine