---
- name: nfs server setup
  hosts: nfs-server
  gather_facts: no
  become: yes
  tasks:
    - name: install nfs-server
      apt:
        name: nfs-server
        state: present

    - name: make directory (nfs_shared)
      file:
        path: /home/vagrant/nfs_shared
        state: directory
        mode: 0777
        
    - name: /etc/exports configuration
      lineinfile:
        path: /etc/exports
        line: /home/vagrant/nfs_shared 192.168.56.0/24(rw,sync)
        # client IP 대역 작성
    
    - name: nfs service restart
      service:
        name: nfs-server
        state: restarted

- name: nfs client setup
  hosts: nfs-client
  gather_facts: no
  become: yes
  tasks:
    - name: install nfs-client
      apt:
        name: nfs-client
        state: present

    - name: make directory_nfs
      file:
        path: /home/vagrant/nfs
        state: directory
        
    - name: make mountpoint
      mount:
        path: /home/vagrant/nfs
        src: 192.168.56.20:/home/vagrant/nfs_shared
        # 소스 IP 작성
        fstype: nfs
        state: mounted

