---
- hosts: devops
  become: yes
  connection: local
  roles: 
    - nginx
    - serverspec
    - docker-server

- hosts: nfs-client
  become: yes
  roles: 
    - nfs-client

- hosts: nfs-server
  become: yes
  roles: 
    - nfs-server