---
- hosts: devops
  become: yes
  connection: local
  roles: 
#    - nginx
#    - serverspec
#    - docker-server
#    - docker-jenkins
#    - docker-harbor
    - docker-mariadb

#- hosts: docker-redmine
#  become: yes
#  roles:
#   - docker-redmine

#- hosts: docker-gitlab
#  become: yes
#  roles:
#    - docker-gitlab

#- hosts: node-exporter
#  become: yes
#  roles:
#    - node-exporter

#- hosts: docker-promethus-grafana
#  become: yes
#  roles:
#    - docker-promethus-grafana