---
- hosts: devops
  become: yes
  connection: local
  roles: 
    # - nginx
    # - serverspec
    # - docker-server
    # - docker-jenkins
    # - docker-harbor

#- hosts: docker-redmine
#  become: yes
#  roles:
#    - docker-redmine

- hosts: docker-gitlab
  become: yes
  roles:
    - docker-gitlab