---
# vars file for docker-jenkins
jenkins:
  name: jenkins
  host: "{{ ansible_user }}"
  group: "{{ ansible_user }}"
  ports: "28080"
  dockercompose:
    directory: "/home/{{ ansible_user }}/docker-compose"
  volumes: 
    directory: "/home/{{ ansible_user }}/volumes"