Vagrant.configure("2") do |config|
 N=2
  config.disksize.size = '40GB'
  config.vm.boot_timeout = 3000
  config.vm.define "bootstrap" do |bootstrap|
    bootstrap.vm.box = "ubuntu/jammy64"
    bootstrap.vm.network "private_network", ip: "192.168.56.10"
    bootstrap.vm.hostname = "bootstrap"

    bootstrap.vm.provider "virtualbox" do |v|
      v.memory = 4096
      v.cpus = 2
	  v.gui = false
    end
  end
  
  config.disksize.size = '40GB'
  config.vm.boot_timeout = 3000
  config.vm.define "master" do |master|
    master.vm.box = "ubuntu/jammy64"
    master.vm.network "private_network", ip: "192.168.56.20"
    master.vm.hostname = "master"

    master.vm.provider "virtualbox" do |v|
	  v.gui = false
      v.memory = 4096
      v.cpus = 2
    end
  end
  
  (1..N).each do |i|
    config.vm.boot_timeout = 3000
    config.disksize.size = '50GB'
    config.vm.define "worker#{i}" do |worker|
      worker.vm.box = "ubuntu/jammy64"
      worker.vm.network "private_network", ip: "192.168.56.2#{i}"
      worker.vm.hostname = "worker#{i}"
      worker.vm.provider "virtualbox" do |v|
	    v.gui = false
        v.memory = 4096
        v.cpus = 4
      end
    end
  end
end