Vagrant.configure("2") do |config|
 N=2
  config.disksize.size = '40GB'
  config.vm.boot_timeout = 3000
  config.vm.define "bootstrap" do |bootstrap|
    bootstrap.vm.box = "ubuntu/jammy64"
    bootstrap.vm.network "public_network", ip: "192.168.56.10"
    bootstrap.vm.hostname = "bootstrap"

    bootstrap.vm.provider "virtualbox" do |v|
      v.memory = 4096
      v.cpus = 2
    end
		
	# 초기 설치 파일
	bootstrap.vm.provision "shell", inline: <<-SCRIPT
      sudo timedatectl set-timezone "Asia/Seoul"
	SCRIPT
  end
  
  config.vm.define "master" do |master|
    master.vm.box = "ubuntu/jammy64"
    master.vm.network "public_network", ip: "192.168.56.20"
    master.vm.hostname = "master"

    master.vm.provider "virtualbox" do |v|
      v.memory = 4096
      v.cpus = 2
    end
	
	# set timezone & disable swap memory & ufw & enable ip forwarding
    master.vm.provision "0", type: "shell", preserve_order: true, privileged: true, inline: <<-EOC
	  sudo apt-get update
	  sudo timedatectl set-timezone "Asia/Seoul"
      sudo swapoff -a
      sudo sed -i '/swap/d' /etc/fstab
      sudo systemctl stop ufw
      sudo systemctl disable ufw
      sudo sed -i "s/#net.ipv4.ip_forward=1/net.ipv4.ip_forward=1/" /etc/sysctl.conf
    EOC
	
	#ssh 설정
	master.vm.provision "shell", inline: <<-SCRIPT
	  sed -i -e "s/PasswordAuthentication no/PasswordAuthentication yes/g" /etc/ssh/sshd_config
      systemctl restart sshd
	SCRIPT
  end
  
  (1..N).each do |i|
    config.vm.boot_timeout = 3000
    config.disksize.size = '50GB'
    config.vm.define "worker#{i}" do |worker|
      worker.vm.box = "ubuntu/jammy64"
      worker.vm.network "public_network", ip: "192.168.56.2#{i}"
      worker.vm.hostname = "worker#{i}"
      worker.vm.provider "virtualbox" do |v|
        v.memory = 4096
        v.cpus = 2
      end
	  
      # set timezone & disable swap memory & ufw & enable ip forwarding
      worker.vm.provision "0", type: "shell", preserve_order: true, privileged: true, inline: <<-EOC
	    sudo apt-get update
	    sudo timedatectl set-timezone "Asia/Seoul"
        sudo swapoff -a
        sudo sed -i '/swap/d' /etc/fstab
        sudo systemctl stop ufw
        sudo systemctl disable ufw
        sudo sed -i "s/#net.ipv4.ip_forward=1/net.ipv4.ip_forward=1/" /etc/sysctl.conf
      EOC
	  
	  #ssh 설정
	  worker.vm.provision "shell", inline: <<-SCRIPT
	    sed -i -e "s/PasswordAuthentication no/PasswordAuthentication yes/g" /etc/ssh/sshd_config
        systemctl restart sshd
	  SCRIPT
    end
  end
end