---
# tasks file for nfs-client
- name: install nfs-client
  apt:
    name: nfs-client
    state: present

- name: make directory_nfs
  file:
    path: "{{nfs.mount.directory}}"
    state: directory
    
- name: make mountpoint
  mount:
    path: "{{nfs.mount.directory}}"
    src: "{{ nfs.server.ip }}:{{ nfs.server.target }}"
    # 소스 IP 작성
    fstype: nfs
    state: mounted